-- ---------------------------------------------------------------------------
-- DKU AI Club — local development database
--
-- This mirrors the shape of the hosted database the site normally talks to: the
-- same tables, the same security-definer functions and the same row-level
-- security policies. The point of the mirror is that a local run exercises the
-- real permission model rather than a permissive stand-in.
--
-- The script is destructive: it drops and rebuilds `public`, and empties the
-- one table this mirror adds inside `auth`. It only ever runs against the
-- dedicated development database.
--
-- There is no account system anywhere in this schema. Access to the panel is a
-- single long key, compared against a hash in `public.site_access`; the panel
-- runs as `anon` for every request, exactly as it does in production. The
-- account objects the hosted database still carries — its own `auth.users`, an
-- `admins` table left over from the account-based panel — are not mirrored,
-- because nothing this site can do reaches them.
--
-- The key this mirror accepts is seeded by `setup.mjs` from `config.mjs`, not
-- here, so that the development key has one definition rather than two.
-- ---------------------------------------------------------------------------

drop schema if exists public cascade;
create schema public;
-- The account tables of the previous design are gone with this script; the
-- stale schemas are dropped so that a rebuild leaves nothing behind.
drop schema if exists local_auth cascade;

-- ---------------------------------------------------------------------------
-- Roles
--
-- `anon` and `authenticated` are the two roles a request can run as. They are
-- cluster-wide, so they are created only when missing. The login role used by
-- the API server is made a member of both so it can `set local role` per
-- request; that is what makes the policies below apply. The site only ever
-- acts as `anon` — `authenticated` exists because the hosted platform has it.
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
end
$$;

do $$
begin
  execute format('grant anon, authenticated to %I', current_user);
end
$$;

-- ---------------------------------------------------------------------------
-- auth schema — the platform's own helpers
--
-- Four columns of `events` and `site_settings` default to `auth.uid()`, which
-- is the hosted database's way of recording who created a row. Since the panel
-- runs anonymously, those columns stay null in practice; the helpers are kept
-- because they are part of the hosted schema and because the column defaults
-- reference one of them.
--
-- Both helpers return `text`, not `uuid`, and both are copied from the hosted
-- database. A uuid-returning `uid()` would make a `text` owner column fail with
-- "operator does not exist: text = uuid".
-- ---------------------------------------------------------------------------

create schema if not exists auth;

create or replace function auth.claims() returns jsonb
language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb)
$$;

create or replace function auth.uid() returns text
language sql stable as $$
  select
  coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::text
$$;

create or replace function auth.email() returns text
language sql stable as $$
  select
  coalesce(
    nullif(current_setting('request.jwt.claim.email', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email')
  )::text
$$;

grant usage on schema auth to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Application tables
-- ---------------------------------------------------------------------------

create table public.events (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  title         text not null,
  summary       text not null default '',
  body          text not null default '',
  category      text not null default 'Event',
  event_date    date not null,
  end_date      date,
  location      text,
  role          text not null default 'host',
  cover_image   text,
  gallery       jsonb not null default '[]'::jsonb,
  tags          text[] not null default '{}'::text[],
  status        text not null default 'draft',
  featured      boolean not null default false,
  source_url    text,
  source_credit text,
  owner_id      text default auth.uid(),
  owner_name    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index events_event_date_idx on public.events (event_date desc);

create table public.site_settings (
  key        text primary key,
  value      jsonb not null default '{}'::jsonb,
  owner_id   text default auth.uid(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Site access — the key that opens the panel
--
-- The panel is opened with one long key and nothing else: no account, no email
-- address, no password to remember, no mailbox that could be used to take it
-- over. What the server keeps is the key's SHA-256, in a table no request from
-- the site can reach — `site_access` is granted to no role and carries
-- row-level security with no policy against it, so the only thing able to read
-- the row is the security-definer function below.
--
-- Storing a hash rather than the key means a database dump does not yield the
-- key, and the key itself is only ever needed where it is compared. What it
-- does not provide is a way back in after the key is lost: there is no recovery
-- address, and re-seeding the hash out of band is the whole recovery procedure.
-- That is the deliberate trade.
--
-- Writes do not go through table policies at all. Every one of them happens
-- inside a function below, which checks the key first and then writes with the
-- table owner's rights, because no role the site can act as has been granted a
-- write on any table. A mistake in these checks therefore fails closed: the
-- worst case is that a legitimate write is refused, not that an illegitimate one
-- succeeds.
-- ---------------------------------------------------------------------------

create table public.site_access (
  only_row   boolean primary key default true check (only_row),
  key_hash   text not null,
  updated_at timestamptz not null default now()
);

alter table public.site_access enable row level security;

/**
 * Whether the supplied key is the site's key.
 *
 * The length floor is not decoration: without it, a stored hash of a short or
 * empty string would be reachable by supplying that same short string.
 */
create or replace function public.site_key_ok(candidate text) returns boolean
language sql stable security definer set search_path to 'public', 'pg_catalog' as $$
  select exists (
    select 1
      from public.site_access a
     where char_length(coalesce(candidate, '')) >= 16
       and a.key_hash = encode(sha256(convert_to(candidate, 'utf8')), 'hex')
  )
$$;

/**
 * The gate every write passes through. Every refusal from here on carries the
 * same code, `42501`, which is also what a missing privilege raises — one
 * sentence in the panel covers both.
 */
create or replace function public.require_site_key(candidate text) returns void
language plpgsql stable security definer set search_path to 'public', 'pg_catalog' as $$
begin
  if not public.site_key_ok(candidate) then
    raise exception 'the site key was not accepted' using errcode = '42501';
  end if;
end
$$;

/** The whole library, drafts and archived records included — for the panel. */
create or replace function public.admin_list_events(p_key text) returns jsonb
language plpgsql stable security definer set search_path to 'public', 'pg_catalog' as $$
begin
  perform public.require_site_key(p_key);
  return coalesce(
    (select jsonb_agg(to_jsonb(e) order by e.event_date desc, e.id desc) from public.events e),
    '[]'::jsonb
  );
end
$$;

/**
 * Creates or overwrites one event, keyed on `slug`.
 *
 * The columns are named one by one rather than taken from the row as sent: the
 * caller's JSON is treated as input to be interpreted, never as a row to be
 * written wholesale. `id`, `created_at` and the ownership columns are therefore
 * not reachable from the panel at all.
 */
create or replace function public.admin_save_event(p_key text, p_event jsonb) returns jsonb
language plpgsql security definer set search_path to 'public', 'pg_catalog' as $$
declare
  saved public.events;
begin
  perform public.require_site_key(p_key);

  insert into public.events (
    slug, title, summary, body, category, event_date, end_date, location, role,
    cover_image, gallery, tags, status, featured, source_url, source_credit, updated_at
  )
  values (
    p_event ->> 'slug',
    p_event ->> 'title',
    coalesce(p_event ->> 'summary', ''),
    coalesce(p_event ->> 'body', ''),
    coalesce(p_event ->> 'category', 'Event'),
    (p_event ->> 'event_date')::date,
    nullif(p_event ->> 'end_date', '')::date,
    nullif(p_event ->> 'location', ''),
    coalesce(p_event ->> 'role', 'host'),
    nullif(p_event ->> 'cover_image', ''),
    coalesce(p_event -> 'gallery', '[]'::jsonb),
    coalesce(array(select jsonb_array_elements_text(p_event -> 'tags')), '{}'::text[]),
    coalesce(p_event ->> 'status', 'draft'),
    coalesce((p_event ->> 'featured')::boolean, false),
    nullif(p_event ->> 'source_url', ''),
    nullif(p_event ->> 'source_credit', ''),
    now()
  )
  on conflict (slug) do update set
    title         = excluded.title,
    summary       = excluded.summary,
    body          = excluded.body,
    category      = excluded.category,
    event_date    = excluded.event_date,
    end_date      = excluded.end_date,
    location      = excluded.location,
    role          = excluded.role,
    cover_image   = excluded.cover_image,
    gallery       = excluded.gallery,
    tags          = excluded.tags,
    status        = excluded.status,
    featured      = excluded.featured,
    source_url    = excluded.source_url,
    source_credit = excluded.source_credit,
    updated_at    = now()
  returning * into saved;

  return to_jsonb(saved);
end
$$;

/** Publishes, drafts or archives one event. */
create or replace function public.admin_set_event_status(
  p_key text,
  p_slug text,
  p_status text
) returns boolean
language plpgsql security definer set search_path to 'public', 'pg_catalog' as $$
declare
  touched integer;
begin
  perform public.require_site_key(p_key);
  if p_status not in ('draft', 'published', 'archived') then
    raise exception 'unknown status: %', p_status using errcode = '22023';
  end if;
  update public.events
     set status = p_status, updated_at = now()
   where slug = p_slug;
  get diagnostics touched = row_count;
  return touched > 0;
end
$$;

/** Removes one event from the library. */
create or replace function public.admin_delete_event(p_key text, p_slug text) returns boolean
language plpgsql security definer set search_path to 'public', 'pg_catalog' as $$
declare
  touched integer;
begin
  perform public.require_site_key(p_key);
  delete from public.events where slug = p_slug;
  get diagnostics touched = row_count;
  return touched > 0;
end
$$;

/** Replaces the site copy as a whole. */
create or replace function public.admin_save_settings(p_key text, p_value jsonb) returns boolean
language plpgsql security definer set search_path to 'public', 'pg_catalog' as $$
begin
  perform public.require_site_key(p_key);
  insert into public.site_settings (key, value, updated_at)
  values ('site', p_value, now())
  on conflict (key) do update set value = excluded.value, updated_at = now();
  return true;
end
$$;

/**
 * Replaces the key itself. The current key is required, so a browser that was
 * left open does not by itself allow the club to be locked out.
 *
 * The length floor matches `site_key_ok`'s: a replacement shorter than this
 * would be accepted by this function and then rejected everywhere else.
 */
create or replace function public.admin_replace_site_key(
  p_current text,
  p_next text
) returns boolean
language plpgsql security definer set search_path to 'public', 'pg_catalog' as $$
begin
  perform public.require_site_key(p_current);
  if char_length(coalesce(p_next, '')) < 24 then
    raise exception 'a site key must be at least 24 characters'
      using errcode = '22023';
  end if;
  update public.site_access
     set key_hash = encode(sha256(convert_to(p_next, 'utf8')), 'hex'),
         updated_at = now();
  return true;
end
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
--
-- These policies are a copy of the ones in the hosted database, statement for
-- statement, including the parts that look redundant — the mirror is only
-- useful if it can fail in the same way the real one can.
-- ---------------------------------------------------------------------------

alter table public.events        enable row level security;
alter table public.site_settings enable row level security;

-- events: the published library is public, and that is all any policy grants.
-- Drafts, archived records, writes and deletions are reachable only through the
-- key-checked functions above, which do not go through policies.
create policy events_read_public on public.events
  for select to anon, authenticated
  using (status = 'published');

-- site_settings: readable by everyone, written by the key-checked function
create policy settings_read_all on public.site_settings
  for select to anon, authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

-- Reading is all the site's own roles can do. Writes belong to the key-checked
-- functions alone, so a write that slipped past them would still be refused for
-- want of a privilege — the two guarantees do not depend on each other.
grant select on public.events, public.site_settings to anon, authenticated;

-- A new function is executable by `public` unless that is taken away, which
-- would expose `require_site_key` — the gate itself, meant to be reached only
-- from inside the functions below — as a callable endpoint. It is revoked
-- first, then the seven the site actually calls are granted back. The owner
-- keeps its own rights either way, so the functions go on calling each other.
revoke execute on function
  public.site_key_ok(text),
  public.require_site_key(text),
  public.admin_list_events(text),
  public.admin_save_event(text, jsonb),
  public.admin_set_event_status(text, text, text),
  public.admin_delete_event(text, text),
  public.admin_save_settings(text, jsonb),
  public.admin_replace_site_key(text, text)
  from public;

grant execute on function
  public.site_key_ok(text),
  public.admin_list_events(text),
  public.admin_save_event(text, jsonb),
  public.admin_set_event_status(text, text, text),
  public.admin_delete_event(text, text),
  public.admin_save_settings(text, jsonb),
  public.admin_replace_site_key(text, text)
  to anon, authenticated;
