/**
 * Builds the SQL that puts the club's event history into the Cloudflare
 * database, and the one row that holds the panel key's hash.
 *
 * The text of every event is read from `public/content/events.json` — the
 * archive that has shipped inside the site all along — rather than retyped, so
 * there is nothing to mistranscribe. The same bytes that are written here were
 * verified against the hosted database by comparing SHA-256 hashes of each
 * write-up (`cloudflare/verify.mjs`).
 *
 *   node cloudflare/seed.mjs                    generates a fresh site key
 *   SITE_KEY=<existing key> node cloudflare/seed.mjs   keeps the one you have
 *
 * Outputs:
 *   cloudflare/seed.sql       replayable into D1, by file
 *   cloudflare/.site-key.txt  the key in plain text, when one was generated
 *
 * Replaying the seed never overwrites an event that is already there, so it is
 * safe to run again after the site has been edited.
 */

import { createHash, randomBytes } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const archivePath = path.join(root, 'public/content/events.json')
const seedPath = path.join(root, 'cloudflare/seed.sql')
const keyPath = path.join(root, 'cloudflare/.site-key.txt')

const sha256Hex = (value) => createHash('sha256').update(value, 'utf8').digest('hex')
const quote = (value) => (value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`)

const COLUMNS = [
  'slug',
  'title',
  'summary',
  'body',
  'category',
  'event_date',
  'end_date',
  'location',
  'role',
  'cover_image',
  'gallery',
  'tags',
  'status',
  'featured',
  'source_url',
  'source_credit',
]

function eventValues(event, index) {
  const row = {
    ...event,
    gallery: JSON.stringify(event.gallery ?? []),
    tags: JSON.stringify(event.tags ?? []),
    status: event.status ?? 'draft',
    featured: event.featured ? 1 : 0,
    id: undefined,
  }
  for (const column of ['slug', 'title', 'event_date']) {
    if (!row[column]) throw new Error(`Event #${index} has no ${column}`)
  }
  return COLUMNS.map((column) => {
    const value = row[column]
    if (column === 'featured') return value ? '1' : '0'
    if (column === 'summary' || column === 'body' || column === 'category') {
      return quote(value ?? '')
    }
    if (column === 'status' || column === 'role') return quote(value)
    return quote(value === undefined || value === '' ? null : value)
  }).join(', ')
}

const archive = JSON.parse(await readFile(archivePath, 'utf8'))
const unique = new Set(archive.map((event) => event.slug))
if (unique.size !== archive.length) throw new Error('The archive holds two events with the same slug')

const supplied = process.env.SITE_KEY?.trim()
const siteKey = supplied || `dkuaiclub-${randomBytes(24).toString('base64url')}`
if (siteKey.length < 24) throw new Error('A site key needs at least 24 characters')

const statements = [
  '-- Generated by cloudflare/seed.mjs — do not edit by hand.',
  '-- Replaying this file never overwrites an event that is already present.',
  '',
  ...archive.map(
    (event, index) =>
      `insert into events (${COLUMNS.join(', ')}) values (${eventValues(event, index)})\n` +
      '  on conflict (slug) do nothing;',
  ),
  '',
  `insert into site_access (only_row, key_hash, updated_at) values (1, ${quote(sha256Hex(siteKey))}, datetime('now'))`,
  '  on conflict (only_row) do update set key_hash = excluded.key_hash, updated_at = datetime(\'now\');',
  '',
]

await writeFile(seedPath, statements.join('\n'), 'utf8')

if (supplied) {
  console.log(`  seed    ${archive.length} events → cloudflare/seed.sql (kept the key you supplied)`)
} else {
  await writeFile(keyPath, `${siteKey}\n`, { mode: 0o600 })
  console.log(`  seed    ${archive.length} events → cloudflare/seed.sql`)
  console.log(`  key     written to cloudflare/.site-key.txt (${siteKey.length} characters)`)
}

const bytes = statements.reduce((total, line) => total + Buffer.byteLength(line), 0)
const longestBody = Math.max(...archive.map((event) => Buffer.byteLength(event.body ?? '')))
console.log(`  size    ${(bytes / 1024).toFixed(0)} kB of SQL; longest write-up ${(longestBody / 1024).toFixed(1)} kB`)
